version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: selva
      MONGO_INITDB_ROOT_PASSWORD: selva123
      MONGO_INITDB_DATABASE: sample-database
    ports:
      -  27017:27017
    volumes:
      -  ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backend

  websvr:
    build: ./work
    container_name: web4mongo
    volumes:
      - ./work/src:/var/www/html
    ports:
      - 80:80
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      -  backend

  mongo-express:
    image: mongo-express
    container_name: mongoex
    ports:
      - 8100:8081     
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: selva
      ME_CONFIG_MONGODB_ADMINPASSWORD: selva123
      ME_CONFIG_MONGODB_URL: mongodb://root:mongopwd@mongo:27017/
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      -  backend

networks:
  backend:
